### PR TITLE
Added 2048 New Rule Game

### PR DESCRIPTION
**Pull request by asbien**

### CODE REVIEW

**Comment by agelber** [comment]
Do you have a better hosted version of this maybe? and possibly a more descriptive name?

**Comment by asbien** [comment]
Yes, this is 2048 new rule game.

**Comment by agelber** [comment]
But do you have a version that is hosted somewhere instead of in jsfiddle?

**Comment by asbien** [comment]
No.

**Comment by agelber** [comment]
Could you make one? On Github Pages maybe?

**Comment by asbien** [comment]
Yes, it's a 2048 New Rule Game, and can be seen to the public.

**Comment by agelber** [comment]
Yeah, I see that, but I mean a page dedicated to it, without all the HTML, JS and CSS parts around it. Take a look at all the other versions for example.

**Comment by agelber** [comment]
Closing due to inactivity

**Pull request closed without merging**
