### PR TITLE
Update variants.yml

### PR DESCRIPTION
**Pull request by CrowofEcstasy**
New 2048 variation

### CODE REVIEW

**Comment by agelber** [comment]
Thanks! But it doesn't seem to be working, the page is getting some sort of error :confused:

**Comment by CrowofEcstasy** [comment]
Yeah, I tried to see if I could do anything, but it looks like all of the 2048s through UsVsTh3m are down. I'll resubmit if it comes back up. 
Thanks for your time!

**Comment by agelber** [comment]
Didn't notice that! In that case, no reason not to merge yours as well. Thanks! 🍻

**Comment by agelber** [comment]
Oh oops, didn't notice this has conflicts. Fix that up and it's good to go!

**Comment by agelber** [comment]
Closing due to inactivity

**Pull request closed without merging**
